on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: 🔨 Dump Autoload
        run: composer dump-autoload

      - name: Clear Cache
        run: |
          php artisan optimize:clear
          php artisan config:clear
          php artisan cache:clear

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Link Storage
        run: php artisan storage:link

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.profitwork-bd.com
          username: masum@profitwork-bd.com
          password: N=0Q69rDN~N?
          exclude: |
            **/.git*
            **/.git*/**
